CREATE SEQUENCE IF NOT EXISTS ID_PHONE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE SEQUENCE IF NOT EXISTS ID_ROLE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE IF NOT EXISTS USERS (
id_user VARCHAR2(400 BYTE) PRIMARY KEY NOT NULL,
name VARCHAR2(400 BYTE),
email VARCHAR2(400 BYTE),
password VARCHAR2(400 BYTE),
create_at DATETIME,
modify_at DATETIME,
last_login DATETIME,
is_active BIT,
token VARCHAR2(400 BYTE));

CREATE TABLE IF NOT EXISTS phones (
id BIGINT PRIMARY KEY NOT NULL,
number_phone VARCHAR2(400 BYTE),
city_code VARCHAR2(400 BYTE),
country_code VARCHAR2(400 BYTE),
id_user VARCHAR2(400 BYTE),
 FOREIGN KEY (id_user) REFERENCES USERS(id_user));

CREATE TABLE IF NOT EXISTS ROLES (
id BIGINT PRIMARY KEY NOT NULL,
authority VARCHAR2(400 BYTE));

CREATE TABLE IF NOT EXISTS USERS_ROLES (
 id_user VARCHAR2(400 BYTE)  NOT NULL,
 id BIGINT  NOT NULL,
 FOREIGN KEY (id_user) REFERENCES USERS(id_user),
 FOREIGN KEY (id) REFERENCES ROLES(id),
 UNIQUE (id_user, id));

